import { Category, Service, User } from './data.model';
const brands = [
  { id: '1', name: 'Aqua' },
  { id: '2', name: 'Bluestone' },
  { id: '3', name: 'Bluestore' },
  { id: '4', name: 'Comfee' },
  { id: '5', name: 'Daikin' },
  { id: '6', name: 'Dalton' },
  { id: '7', name: 'Electrolux' },
  { id: '8', name: 'Kangaroo' },
  { id: '9', name: 'Khác' },
  { id: '10', name: 'LG' },
  { id: '11', name: 'Midea' },
  { id: '12', name: 'Mishio' },
  { id: '13', name: 'Mobell' },
  { id: '14', name: 'Nanomax' },
  { id: '15', name: 'Panasonic' },
  { id: '16', name: 'Philips' },
  { id: '17', name: 'Samsung' },
  { id: '18', name: 'Sharp' },
  { id: '19', name: 'Sony' },
  { id: '20', name: 'Sunhouse' },
  { id: '21', name: 'TCL' },
  { id: '22', name: 'Toshiba' },
  { id: '23', name: 'Xiaomi' },
  { id: '24', name: 'Zenbos' },
];
const requests = [
  { id: '1', name: 'Thay màn hình' },
  { id: '2', name: 'Âm thanh rè' },
  { id: '3', name: 'Bật không lên' },
  { id: '4', name: 'Bật nhưng không hút' },
  { id: '5', name: 'Bị chảy nước' },
  { id: '6', name: 'Bị rè' },
  { id: '7', name: 'Cửa mở không được' },
  { id: '8', name: 'Đèn không lên' },
  { id: '9', name: 'Gãy cửa' },
  { id: '10', name: 'Giặt không sạch' },
  { id: '11', name: 'Hư cảm ứng' },
  { id: '12', name: 'Hư đồng hồ' },
  { id: '13', name: 'Khác' },
  { id: '14', name: 'Không có đèn' },
  { id: '15', name: 'Không có loa' },
  { id: '16', name: 'Không đóng được cửa' },
  { id: '17', name: 'Không kết nối được với thiết bị' },
  { id: '18', name: 'Không khóa cửa' },
  { id: '19', name: 'Không lạnh' },
  { id: '20', name: 'Không lên đèn' },
  { id: '21', name: 'Không nhận tín hiệu' },
  { id: '22', name: 'Không nóng' },
  { id: '23', name: 'Khống nóng' },
  { id: '24', name: 'Không quay' },
  { id: '25', name: 'Không xả nước' },
  { id: '26', name: 'Mất linh kiện' },
  { id: '27', name: 'Máy hút yếu' },
  { id: '28', name: 'Ngắt âm thanh giữa chừng' },
  { id: '29', name: 'Quạt không quay' },
  { id: '30', name: 'Quạt quay kêu' },
  { id: '31', name: 'Sai màu' },
  { id: '32', name: 'Treo máy' },
  { id: '33', name: 'Tủ không mát' },
  { id: '34', name: 'Vỡ đĩa' },
  { id: '35', name: 'Vùng nóng không hoạt động' },
];

const devicesRequests = [
  { id: '1', deviceID: '1', requestID: '18' },
  { id: '2', deviceID: '1', requestID: '25' },
  { id: '3', deviceID: '1', requestID: '24' },
  { id: '4', deviceID: '1', requestID: '10' },
  { id: '5', deviceID: '1', requestID: '3' },
  { id: '6', deviceID: '1', requestID: '13' },
  { id: '7', deviceID: '2', requestID: '6' },
  { id: '8', deviceID: '2', requestID: '3' },
  { id: '9', deviceID: '2', requestID: '31' },
  { id: '10', deviceID: '2', requestID: '15' },
  { id: '11', deviceID: '2', requestID: '21' },
  { id: '12', deviceID: '2', requestID: '13' },
  { id: '13', deviceID: '3', requestID: '33' },
  { id: '14', deviceID: '3', requestID: '8' },
  { id: '15', deviceID: '3', requestID: '7' },
  { id: '16', deviceID: '3', requestID: '9' },
  { id: '17', deviceID: '3', requestID: '26' },
  { id: '18', deviceID: '3', requestID: '13' },
  { id: '19', deviceID: '4', requestID: '5' },
  { id: '20', deviceID: '4', requestID: '30' },
  { id: '21', deviceID: '4', requestID: '19' },
  { id: '22', deviceID: '4', requestID: '29' },
  { id: '23', deviceID: '4', requestID: '3' },
  { id: '24', deviceID: '4', requestID: '13' },
  { id: '25', deviceID: '5', requestID: '12' },
  { id: '26', deviceID: '5', requestID: '22' },
  { id: '27', deviceID: '5', requestID: '14' },
  { id: '28', deviceID: '5', requestID: '3' },
  { id: '29', deviceID: '5', requestID: '34' },
  { id: '30', deviceID: '5', requestID: '13' },
  { id: '31', deviceID: '6', requestID: '3' },
  { id: '32', deviceID: '6', requestID: '22' },
  { id: '33', deviceID: '6', requestID: '35' },
  { id: '34', deviceID: '6', requestID: '32' },
  { id: '35', deviceID: '6', requestID: '11' },
  { id: '36', deviceID: '6', requestID: '13' },
  { id: '37', deviceID: '7', requestID: '3' },
  { id: '38', deviceID: '7', requestID: '12' },
  { id: '39', deviceID: '7', requestID: '23' },
  { id: '40', deviceID: '7', requestID: '16' },
  { id: '41', deviceID: '7', requestID: '20' },
  { id: '42', deviceID: '7', requestID: '13' },
  { id: '43', deviceID: '8', requestID: '3' },
  { id: '44', deviceID: '8', requestID: '1' },
  { id: '45', deviceID: '8', requestID: '21' },
  { id: '46', deviceID: '8', requestID: '17' },
  { id: '47', deviceID: '8', requestID: '28' },
  { id: '48', deviceID: '8', requestID: '13' },
  { id: '49', deviceID: '9', requestID: '3' },
  { id: '50', deviceID: '9', requestID: '21' },
  { id: '51', deviceID: '9', requestID: '4' },
  { id: '52', deviceID: '9', requestID: '27' },
  { id: '53', deviceID: '9', requestID: '2' },
  { id: '54', deviceID: '9', requestID: '13' },
];
const devices = [
  { id: '1', name: 'Sửa máy giặt' },
  { id: '2', name: 'Sửa tivi' },
  { id: '3', name: 'Sửa tủ lạnh' },
  { id: '4', name: 'Sửa máy lạnh' },
  { id: '5', name: 'Sửa lò vi sóng' },
  { id: '6', name: 'Sửa bếp từ' },
  { id: '7', name: 'Sửa lò nướng' },
  { id: '8', name: 'Sửa loa vi tính' },
  { id: '9', name: 'Sửa máy hút bụi' },
];
const services: Service[] = [
  { id: '1', name: 'Thay màn hình', price: 650000 },
  { id: '2', name: 'Sửa cốt máy giặt', price: 250000 },
  { id: '3', name: 'Sửa motor xả nước', price: 450000 },
  { id: '4', name: 'Sửa van nước', price: 240000 },
  { id: '5', name: 'Sửa phao cảm biến', price: 350000 },
  { id: '6', name: 'Sửa ty treo', price: 90000 },
  { id: '7', name: 'Sửa motor', price: 30000 },
  { id: '8', name: 'Vệ sinh máy', price: 90000 },
  { id: '9', name: 'Sửa dây curoa ', price: 40000 },
  { id: '10', name: 'Sửa tụ máy', price: 50000 },
  { id: '11', name: 'Hư cao áp ', price: 200000 },
  { id: '12', name: 'Hư nguồn ', price: 250000 },
  { id: '13', name: 'Hư bo khiển', price: 300000 },
  { id: '14', name: 'Thay cổng HDMI', price: 350000 },
  { id: '15', name: 'Thay cảm biến hồng ngoại', price: 530000 },
  { id: '16', name: 'Thay loa tivi', price: 570000 },
  { id: '17', name: 'Thay phim màn hình', price: 250000 },
  { id: '18', name: 'Thay đèn LED cho', price: 950000 },
  { id: '19', name: 'Sửa board', price: 50000 },
  { id: '20', name: 'Vệ sinh tivi', price: 60000 },
  { id: '21', name: 'Thay ron', price: 580000 },
  { id: '22', name: 'Vệ sinh tủ lạnh', price: 540000 },
  { id: '23', name: 'Thay thế các linh kiện', price: 450000 },
  { id: '24', name: 'Sửa tủ đông', price: 80000 },
  { id: '25', name: 'Sửa tủ mát', price: 840000 },
  { id: '26', name: 'Thay quạt dàn nóng', price: 70000 },
  { id: '27', name: 'Thay block tủ lạnh', price: 70000 },
  { id: '28', name: 'Hàn dàn + nạp gas', price: 45000 },
  { id: '29', name: 'Thay điện trở', price: 45000 },
  { id: '30', name: 'Sửa board', price: 45000 },
  { id: '31', name: 'Sửa mất nguồn', price: 453000 },
  { id: '32', name: 'Sửa board dàn lạnh (mono)', price: 730000 },
  { id: '33', name: 'Sửa board dàn lạnh (inverter)', price: 730000 },
  { id: '34', name: 'Thay cảm biến to phòng/dàn', price: 73000 },
  { id: '35', name: 'Thay hồng ngoại nhận tín hiệu', price: 710000 },
  { id: '36', name: 'Thay quạt', price: 70000 },
  { id: '37', name: 'Thay mô tơ lá đảo gió', price: 370000 },
  { id: '38', name: 'Thay tụ quạt dàn nóng', price: 670000 },
  { id: '39', name: 'Nạp ga', price: 80000 },
  { id: '40', name: 'Vệ sinh máy lạnh', price: 280000 },
  { id: '41', name: 'Thay cục sóng', price: 840000 },
  { id: '42', name: 'Sửa board', price: 82000 },
  { id: '43', name: 'Thay cầu chì', price: 86000 },
  { id: '44', name: 'Thay Timer', price: 18000 },
  { id: '45', name: 'Sơn + xử lý rỉ sét', price: 98000 },
  { id: '46', name: 'Lá chắn sóng', price: 88000 },
  { id: '47', name: 'Moter đĩa', price: 84000 },
  { id: '48', name: 'Đĩa thuỷ tinh lò vi sóng', price: 100000 },
  { id: '49', name: 'Biến áp', price: 100000 },
  { id: '50', name: 'Tụ lò vi sóng', price: 150000 },
  { id: '51', name: 'Không nhận nồi', price: 120000 },
  { id: '52', name: 'Sửa dây', price: 100000 },
  { id: '53', name: 'Sửa cảm ứng', price: 80000 },
  { id: '54', name: 'Thay quạt', price: 80000 },
  { id: '55', name: 'Vùng nấu không hoạt động', price: 300000 },
  { id: '56', name: 'Bếp từ kêu to', price: 300000 },
  { id: '57', name: 'Lỗi treo máy', price: 300000 },
  { id: '58', name: 'Sửa nguồn', price: 300000 },
  { id: '59', name: 'Thay thanh nhiệt', price: 300000 },
  { id: '60', name: 'Thay kính lò nướng', price: 50000 },
  { id: '61', name: 'Sửa nguồn', price: 50000 },
  { id: '62', name: 'Sửa đèn tín hiệu', price: 450000 },
  { id: '63', name: 'Sửa đèn trong lò', price: 450000 },
  { id: '64', name: 'Đánh lửa có vấn đề', price: 450000 },
  { id: '65', name: 'Làm nóng bị mài mòn', price: 450000 },
  { id: '66', name: 'Nhiệt độ không đúng', price: 450000 },
  { id: '67', name: 'Vệ sinh lò nướng', price: 50000 },
  { id: '68', name: 'Vệ sinh lò', price: 50000 },
  { id: '69', name: 'Thay tụ điện', price: 500000 },
  { id: '70', name: 'Hư cuộn dây đồng', price: 500000 },
  { id: '71', name: 'Thay jack cắm', price: 520000 },
  { id: '72', name: 'Sửa nguồn', price: 650000 },
  { id: '73', name: 'Sửa âm lượng', price: 650000 },
  { id: '74', name: 'Thay thế motor', price: 50000 },
  { id: '75', name: 'Sửa mạch điều khiển', price: 750000 },
  { id: '76', name: 'Sửa nguồn điện', price: 73000 },
  { id: '77', name: 'Máy hút bị yếu', price: 350000 },
  { id: '78', name: 'Máy chạy nhưng không hút', price: 50000 },
];
const devicesBrands = [
  { id: '1', deviceID: '1', brandID: '1' },
  { id: '2', deviceID: '1', brandID: '17' },
  { id: '3', deviceID: '1', brandID: '22' },
  { id: '4', deviceID: '1', brandID: '10' },
  { id: '5', deviceID: '1', brandID: '15' },
  { id: '6', deviceID: '1', brandID: '9' },
  { id: '7', deviceID: '2', brandID: '19' },
  { id: '8', deviceID: '2', brandID: '17' },
  { id: '9', deviceID: '2', brandID: '10' },
  { id: '10', deviceID: '2', brandID: '21' },
  { id: '11', deviceID: '2', brandID: '13' },
  { id: '12', deviceID: '2', brandID: '9' },
  { id: '13', deviceID: '3', brandID: '1' },
  { id: '14', deviceID: '3', brandID: '17' },
  { id: '15', deviceID: '3', brandID: '15' },
  { id: '16', deviceID: '3', brandID: '22' },
  { id: '17', deviceID: '3', brandID: '18' },
  { id: '18', deviceID: '3', brandID: '9' },
  { id: '19', deviceID: '4', brandID: '5' },
  { id: '20', deviceID: '4', brandID: '10' },
  { id: '21', deviceID: '4', brandID: '17' },
  { id: '22', deviceID: '4', brandID: '18' },
  { id: '23', deviceID: '4', brandID: '22' },
  { id: '24', deviceID: '4', brandID: '9' },
  { id: '25', deviceID: '5', brandID: '18' },
  { id: '26', deviceID: '5', brandID: '22' },
  { id: '27', deviceID: '5', brandID: '7' },
  { id: '28', deviceID: '5', brandID: '15' },
  { id: '29', deviceID: '5', brandID: '2' },
  { id: '30', deviceID: '5', brandID: '9' },
  { id: '31', deviceID: '6', brandID: '20' },
  { id: '32', deviceID: '6', brandID: '7' },
  { id: '33', deviceID: '6', brandID: '8' },
  { id: '34', deviceID: '6', brandID: '11' },
  { id: '35', deviceID: '6', brandID: '4' },
  { id: '36', deviceID: '6', brandID: '9' },
  { id: '37', deviceID: '7', brandID: '20' },
  { id: '38', deviceID: '7', brandID: '16' },
  { id: '39', deviceID: '7', brandID: '12' },
  { id: '40', deviceID: '7', brandID: '3' },
  { id: '41', deviceID: '7', brandID: '18' },
  { id: '42', deviceID: '7', brandID: '9' },
  { id: '43', deviceID: '8', brandID: '13' },
  { id: '44', deviceID: '8', brandID: '6' },
  { id: '45', deviceID: '8', brandID: '14' },
  { id: '46', deviceID: '8', brandID: '10' },
  { id: '47', deviceID: '8', brandID: '24' },
  { id: '48', deviceID: '8', brandID: '9' },
  { id: '49', deviceID: '9', brandID: '7' },
  { id: '50', deviceID: '9', brandID: '17' },
  { id: '51', deviceID: '9', brandID: '15' },
  { id: '52', deviceID: '9', brandID: '23' },
  { id: '53', deviceID: '9', brandID: '16' },
  { id: '54', deviceID: '9', brandID: '9' },
];
const categories: Category[] = [
  {
    ...devices[0],
    thumbnail: 'cate-1.svg',
    services: services.filter((_, index) => index < 10),
  },
  {
    ...devices[1],
    thumbnail: 'cate-2.svg',
    services: services.filter((_, index) => index >= 10 && index < 20),
  },
  {
    ...devices[2],
    thumbnail: 'cate-3.svg',
    services: services.filter((_, index) => index >= 20 && index < 30),
  },
  {
    ...devices[3],
    thumbnail: 'cate-4.svg',
    services: services.filter((_, index) => index >= 30 && index < 40),
  },
  {
    ...devices[4],
    thumbnail: 'cate-5.svg',
    services: services.filter((_, index) => index >= 40 && index < 50),
  },
  {
    ...devices[5],
    thumbnail: 'cate-6.svg',
    services: services.filter((_, index) => index >= 50 && index < 58),
  },
  {
    ...devices[6],
    thumbnail: 'cate-7.svg',
    services: services.filter((_, index) => index >= 58 && index < 67),
  },
  {
    ...devices[7],
    thumbnail: 'cate-8.svg',
    services: services.filter((_, index) => index >= 67 && index < 73),
  },
  {
    ...devices[8],
    thumbnail: 'cate-9.svg',
    services: services.filter((_, index) => index >= 73 && index < 78),
  },
];

const users: User[] = [
  {
    id: '1',
    distance: 5,
    time: 34,
    phone: '0909123123',
    rating: 5,
    name: 'Võ Thành Nhân',
    avatar: 'avatar-0.jpg',
    address: '55B Trần Quang Khải',
    province: 'Q1, TP.HCM',
    categories: categories,
  },
  {
    id: '2',
    distance: 4.3,
    time: 30,
    phone: '0909123675',
    rating: 4.5,
    name: 'Phạm Long',
    avatar: 'avatar-1.png',
    address: '75B Nguyễn Kiệm',
    province: 'Q2, TP.HCM',
    categories: categories,
  },
  {
    id: '3',
    distance: 1.2,
    time: 20,
    phone: '0909134123',
    rating: 5,
    name: 'Dương Nguyên',
    avatar: 'avatar-2.jpg',
    address: '32 Dương Lâm',
    province: 'Gò Vấp, TP.HCM',
    categories: categories,
  },
  {
    id: '4',
    distance: 3.2,
    time: 25,
    phone: '0909657763',
    rating: 3.5,
    name: 'Đỗ Đạt',
    avatar: 'avatar-3.png',
    address: '32 Nhà Gỗ',
    province: 'Tân Bình, TP.HCM',
    categories: categories,
  },
  {
    id: '5',
    distance: 5.3,
    time: 20,
    phone: '0909123123',
    rating: 5,
    name: 'Đặng Nhân',
    avatar: 'avatar-4.png',
    address: '32 Phan Tôn',
    province: 'Q4, TP.HCM',
    categories: categories,
  },
  {
    id: '6',
    distance: 3,
    time: 32,
    phone: '0909123123',
    rating: 4,
    name: 'Hà Tâm',
    avatar: 'avatar-5.png',
    address: '32 Võ Văn Ngân',
    province: 'Thủ Đức, TP.HCM',
    categories: categories,
  },
  {
    id: '7',
    distance: 3.8,
    time: 35,
    phone: '0909123123',
    rating: 4,
    name: 'Lê Văn Đạt',
    avatar: 'avatar-6.png',
    address: '4 Lê Văn Việt',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
  {
    id: '8',
    distance: 8.2,
    time: 45,
    phone: '0909123123',
    rating: 5,
    name: 'Đỗ Trương Đông',
    avatar: 'avatar-7.jpg',
    address: '30 Man Thiện',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
  {
    id: '9',
    distance: 9.2,
    time: 50,
    phone: '0909123123',
    rating: 4,
    name: 'Hà Mẫn Đạt',
    avatar: 'avatar-8.jpg',
    address: '20 Lã Xuân Oai',
    province: 'Q9, TP.HCM',
    categories: categories,
  },
];
const servicesWithCategoryId = services.map((service, index) => {
  if (index < 10) service.categoryId = '1';
  else if (index < 20) service.categoryId = '2';
  else if (index < 30) service.categoryId = '3';
  else if (index < 40) service.categoryId = '4';
  else if (index < 50) service.categoryId = '5';
  else if (index < 58) service.categoryId = '6';
  else if (index < 67) service.categoryId = '7';
  else if (index < 73) service.categoryId = '8';
  else if (index < 78) service.categoryId = '9';
  return service;
});
const searchHistory = ['máy giặt', 'tủ lạnh', 'sửa tivi'];
export const DATABASE = {
  users,
  services: servicesWithCategoryId,
  categories,
  searchHistory,
  brands,
  requests,
  devicesRequests,
  devicesBrands,
};
